### ISSUE TITLE
Can't get your example run

### ISSUE THREAD

**Issue by rottmann** [mallocator/Winston-Rolling-File-Appender#2]
winston 2.3.1
rolling-file-transport: 1.1.0

```
Error: Cannot add unknown transport: RollingFile
    at /app/node_modules/winston/lib/winston/container.js:68:15
```

Why did you extend winston.Transport with your own class?

You can add a normal Transport like winston itself does it: https://github.com/winstonjs/winston/blob/master/lib/winston/transports/file.js

**Comment by mallocator** [comment]
Weird I'm not getting any issues when running against the latest winston. 

This extensions was created back when winston was did not have file rollovers built in. I'm mostly just maintaining it now for the few people that might still reference it, but if you can get what you need from the main module, by all means make use of it.
